version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/ride-sharing-data-dir:/data/db

  backend:
    build: ./backend2
    container_name: ride-sharing-backend
    restart: always
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    command: ["pm2-runtime", "start", "app.js", "--name", "ride-sharing-backend"]

  frontend:
    build: ./frontend2/ride-sharing
    container_name: ride-sharing-frontend
    restart: always
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - backend
    command: ["pm2-runtime", "start", "npm", "--name", "ride-sharing-frontend", "--", "run", "start"]
